# Generated by Django 4.2.6 on 2023-12-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_tag_post_image_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tag_slug',
            field=models.SlugField(default='', max_length=250, unique_for_date='publish'),
        ),
    ]
